[package]
name = "server_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.2", features = ["full"] }
actix-web = "4.5.1"
tokio-stream = "0.1.12"
rand = "0.8.5"
